################################################################################
# Stage 1 - 8GB ################################################################
################################################################################
FROM nvcr.io/nvidia/cuda:12.8.1-cudnn-runtime-ubuntu22.04 AS ros2-image

# Tell apt (and other Debian tools) not to prompt for user input during package installs
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install basic dependencies
RUN apt update \
    && apt install -y --no-install-recommends \
        wget gosu htop vim ruby tmux net-tools iproute2 iputils-ping netcat-openbsd \
        python3-pip python3-venv \
        mesa-utils \
    && gem install tmuxinator \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# Install ROS2 Humble
# Based on https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debs.html
RUN apt update \
    && apt install -y --no-install-recommends \
        locales \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8
RUN apt update \
    && apt install -y --no-install-recommends \
        software-properties-common curl \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu \
    $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt update \
    && apt install -y --no-install-recommends \
        ros-humble-desktop ros-dev-tools \
        ros-humble-bondcpp ros-humble-ament-cmake-clang-format \
        ros-humble-vision-msgs \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*
RUN echo "source /opt/ros/humble/setup.bash" >> /root/.bashrc
RUN rosdep init

################################################################################
# Stage 2 - 8+GB ###############################################################
################################################################################
FROM ros2-image AS ros2-qgc-zenoh-image

# QGroundControl (as qgcuser)
# Based on https://docs.qgroundcontrol.com/master/en/qgc-user-guide/getting_started/download_and_install.html
WORKDIR /
RUN useradd -m -s /bin/bash qgcuser
RUN usermod -aG dialout qgcuser
# RUN apt-get remove modemmanager -y
RUN apt update \
    && apt install -y --no-install-recommends \
        gstreamer1.0-plugins-bad gstreamer1.0-libav gstreamer1.0-gl \
        libfuse2 \
        libxcb-xinerama0 libxkbcommon-x11-0 libxcb-cursor-dev \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*
RUN wget https://d176tv9ibo4jno.cloudfront.net/latest/QGroundControl-x86_64.AppImage && \
    chmod +x /QGroundControl-x86_64.AppImage && \
    /QGroundControl-x86_64.AppImage --appimage-extract && \
    rm /QGroundControl-x86_64.AppImage
# Run with $ gosu qgcuser /squashfs-root/AppRun

# Install Zenoh
RUN echo "deb [trusted=yes] https://download.eclipse.org/zenoh/debian-repo/ /" | sudo tee -a /etc/apt/sources.list > /dev/null
RUN apt-get update && \
    apt-get install -y zenoh-bridge-ros2dds \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

################################################################################
# Stage 3 - 8+GB ###############################################################
################################################################################
FROM ros2-qgc-zenoh-image AS ros2-qgc-zenoh-gst-pymavlink-image

# Add GStreamer packages to stream the cameras to the aircraft containers
RUN apt update \
    && apt install -y --no-install-recommends \
        gstreamer1.0-tools gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-libav \
        python3-gi gir1.2-gst-plugins-base-1.0 gir1.2-gstreamer-1.0 \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# MAVProxy 
RUN apt update \
    && apt install -y --no-install-recommends \
        python3-dev python3-opencv python3-wxgtk4.0 python3-pip python3-matplotlib python3-lxml python3-pygame \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir --upgrade pip \
    && pip3 install --no-cache-dir --resume-retries 5 "numpy<2" future mavproxy 

# Add pymavlink to emulate the ground system using telemetry data
RUN pip3 install --no-cache-dir --upgrade pip \
    && pip3 install --no-cache-dir --resume-retries 5 pymavlink pyserial
# Check with $ python3 -c "import pymavlink; print(pymavlink.__version__)"

################################################################################
# Stage 4 - 8+GB ###############################################################
################################################################################
FROM ros2-qgc-zenoh-gst-pymavlink-image AS ground-dev-image

# Install wmctrl and xrandr to resize QGC window
RUN apt update \
    && apt install -y --no-install-recommends \
        wmctrl x11-xserver-utils \
    && apt clean \
    && rm -rf /var/lib/apt/lists/*

# Add MAVLink 2 C library
COPY /github_clones/c_library_v2 /usr/local/include/mavlink/

# Build the ROS 2 workspace
COPY ground/ground_ws/src /aas/ground_ws/src
WORKDIR /aas/ground_ws
RUN rosdep update
RUN rosdep install --from-paths src/ --ignore-src --rosdistro humble -y
# Explicitly use bash, not sh, to source and build the workspace
RUN bash -c "source /opt/ros/humble/setup.bash && (source /aas/github_ws/install/setup.bash || true) && colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release"

# Copy resources and configuration files from this repository
COPY ground/ground_resources/ /aas/ground_resources
COPY ground/ground_resources/patches/QGroundControl.ini /home/qgcuser/.config/QGroundControl/QGroundControl.ini

# Source the workspaces
RUN echo "source /aas/ground_ws/install/setup.bash" >> /root/.bashrc
# If needed (but already in .bashrc) $ source /opt/ros/humble/setup.bash && source /aas/ground_ws/install/setup.bash

# Final config
WORKDIR /aas
COPY ground/ground.yml.erb /aas/ground.yml.erb
ENTRYPOINT ["tmuxinator", "start", "-p", "/aas/ground.yml.erb"]
